services:
  postgres:
    image: postgres:16
    container_name: transparent-fund-ledger-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: transparent_fund
      POSTGRES_USER: fund_admin
      POSTGRES_PASSWORD: fund_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

volumes:
  postgres_data: